name: 'banking_analytics'
version: '1.0.0'
config-version: 2

profile: 'banking_analytics'

model-paths: ["models"]
test-paths: ["tests"]
macro-paths: ["macros"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  banking_analytics:
    staging:
      +materialized: view
    gold:
      +materialized: table
