version: 2

sources:
  - name: raw
    description: "Raw data ingested from CSV/parquet files"
    tables:
      - name: raw_complaints
        description: "Raw consumer complaints data"
        columns:
          - name: complaint_id
            tests:
              - not_null
          - name: date_received
            tests:
              - not_null
          - name: product
            tests:
              - not_null
          - name: company
            tests:
              - not_null

      - name: raw_call_reports
        description: "Raw quarterly bank financial data"
        columns:
          - name: quarter
            tests:
              - not_null
          - name: bank_name
            tests:
              - not_null
          - name: bank_id
            tests:
              - not_null
